cargo-features = ["edition2021"]

[package]
name = "anders-kluring-3"
version = "0.1.0"
edition = "2021"

[features]
default = ["parallel"]
parallel = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5.1"
